<?php

return [

    /*
    |--------------------------------------------------------------------------
    | ISO 3166-1 alpha-2 country → ISO 4217 currency
    |--------------------------------------------------------------------------
    |
    | Used to pick a default display currency from the visitor's IP country.
    | If the mapped currency is not in shop.currency.supported, the store
    | falls back to the base currency (USD).
    |
    */

    'country_map' => [
        'AD' => 'EUR',
        'AE' => 'AED',
        'AT' => 'EUR',
        'AU' => 'AUD',
        'BD' => 'BDT',
        'BE' => 'EUR',
        'BH' => 'BHD',
        'BR' => 'BRL',
        'BV' => 'NOK',
        'CA' => 'CAD',
        'CC' => 'AUD',
        'CH' => 'CHF',
        'CK' => 'NZD',
        'CN' => 'CNY',
        'CX' => 'AUD',
        'CY' => 'EUR',
        'DE' => 'EUR',
        'DK' => 'DKK',
        'EE' => 'EUR',
        'EG' => 'EGP',
        'ES' => 'EUR',
        'FI' => 'EUR',
        'FO' => 'DKK',
        'FR' => 'EUR',
        'GB' => 'GBP',
        'GG' => 'GBP',
        'GL' => 'DKK',
        'GR' => 'EUR',
        'HK' => 'HKD',
        'HM' => 'AUD',
        'ID' => 'IDR',
        'IE' => 'EUR',
        'IM' => 'GBP',
        'IN' => 'INR',
        'IT' => 'EUR',
        'JE' => 'GBP',
        'KI' => 'AUD',
        'KW' => 'KWD',
        'LI' => 'CHF',
        'LK' => 'LKR',
        'LS' => 'ZAR',
        'LT' => 'EUR',
        'LU' => 'EUR',
        'LV' => 'EUR',
        'MC' => 'EUR',
        'ME' => 'EUR',
        'MT' => 'EUR',
        'MX' => 'MXN',
        'MY' => 'MYR',
        'NA' => 'ZAR',
        'NF' => 'AUD',
        'NG' => 'NGN',
        'NL' => 'EUR',
        'NO' => 'NOK',
        'NR' => 'AUD',
        'NU' => 'NZD',
        'NZ' => 'NZD',
        'OM' => 'OMR',
        'PH' => 'PHP',
        'PK' => 'PKR',
        'PL' => 'PLN',
        'PN' => 'NZD',
        'PT' => 'EUR',
        'QA' => 'QAR',
        'SA' => 'SAR',
        'SE' => 'SEK',
        'SG' => 'SGD',
        'SI' => 'EUR',
        'SJ' => 'NOK',
        'SK' => 'EUR',
        'SM' => 'EUR',
        'SZ' => 'ZAR',
        'TH' => 'THB',
        'TK' => 'NZD',
        'TR' => 'TRY',
        'TV' => 'AUD',
        'US' => 'USD',
        'VA' => 'EUR',
        'XK' => 'EUR',
        'ZA' => 'ZAR',
    ],

];
